# Change these first
owner: tryrocket-cloud # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repositoryaasc

sites:
  - name: Dashboard
    url: https://tryrocket.cloud
  - name: Docs
    url: https://docs.tryrocket.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tryrocket.cloud
  #baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  # Available themes are light, dark, night or ocean.
  theme: night

  name: Rocket Cloud
  introTitle: "**Rocket Cloud**'s Status Page"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# https://upptime.js.org/docs/faq/#how-do-i-remove-the-powered-by-upptime-in-the-foeoter-of-my-website
i18n:
  footer: ""
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
